import { toolCategories } from "./site-content";
import manifest from "./tool-manifest.json";

/**
 * Counts the MCP tools this server exposes.
 *
 * The numbers come from `tool-manifest.json`, which is generated by booting
 * the real server and listing its tools (`bun run tools:manifest`). Counting
 * registration call sites in source over-counted, because some registrations
 * are conditional on wallet mode and never run.
 */

export const allToolNames: readonly string[] = manifest.tools;

/** Tools whose name starts with `<prefix>_`. */
function matchesPrefix(name: string, prefixes: readonly string[]): boolean {
	return prefixes.some((prefix) => name.startsWith(`${prefix}_`));
}

/** Tools belonging to a category, by name prefix plus any explicit members. */
export function toolsInCategory(category: {
	prefixes: readonly string[];
	tools?: readonly string[];
}): string[] {
	return allToolNames.filter(
		(name) =>
			matchesPrefix(name, category.prefixes) ||
			(category.tools?.includes(name) ?? false),
	);
}

export interface ToolCounts {
	/** Every tool the server exposes. */
	total: number;
	/** Tool count keyed by category key. */
	byCategory: Record<string, number>;
}

let cached: ToolCounts | null = null;

export function getToolCounts(): ToolCounts {
	if (cached) return cached;

	const byCategory: Record<string, number> = {};
	for (const category of toolCategories) {
		byCategory[category.key] = toolsInCategory(category).length;
	}

	cached = { total: allToolNames.length, byCategory };
	return cached;
}

/** Count for one category, or 0 when it is unknown. */
export function countTools(counts: ToolCounts, categoryKey: string): number {
	return counts.byCategory[categoryKey] ?? 0;
}

/**
 * Renders a total as an approximate floor, so the headline reads "80+" rather
 * than a precise figure that invites nitpicking. Returns null below one bucket.
 */
export function approximateTotal(total: number, bucket = 10): string | null {
	const floored = Math.floor(total / bucket) * bucket;
	return floored >= bucket ? `${floored}+` : null;
}
